# Generated by Django 4.2.4 on 2023-11-02 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='After_complain_resolved_file',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('after_complain_resolve_file', models.FileField(upload_to='after_complain_resolved_file/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'After Complain Resolved Files',
                'db_table': 'after_complain_resolved_file',
            },
        ),
        migrations.CreateModel(
            name='Before_complain_resolved_file',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('before_complain_resolve_file', models.FileField(upload_to='before_complain_resolved_file/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Before Complain Resolved Files',
                'db_table': 'before_complain_resolved_file',
            },
        ),
        migrations.CreateModel(
            name='Complain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_account_no', models.CharField(max_length=100)),
                ('complain_title', models.CharField(max_length=100)),
                ('complain_description', models.TextField()),
                ('is_public', models.BooleanField(default=False)),
                ('is_valid', models.BooleanField(default=False)),
                ('is_edited', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('after_complain_resolved_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complain_app.after_complain_resolved_file')),
                ('before_complain_resolved_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complain_app.before_complain_resolved_file')),
            ],
            options={
                'verbose_name_plural': 'Complains',
                'db_table': 'complain',
            },
        ),
        migrations.CreateModel(
            name='Complain_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Complain Categories',
                'db_table': 'complain_category',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('office_reg_no', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('website', models.CharField(max_length=100)),
                ('help_line', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='organization_logo/')),
                ('district', models.CharField(max_length=100)),
                ('taluka', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Organizations',
                'db_table': 'organization',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('office_no', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.IntegerField(max_length=100)),
                ('website', models.CharField(max_length=100)),
                ('help_line', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='department_logo/')),
                ('district', models.CharField(max_length=100)),
                ('taluka', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fk_organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complain_app.organization')),
            ],
            options={
                'verbose_name_plural': 'Departments',
                'db_table': 'department',
            },
        ),
        migrations.CreateModel(
            name='Complain_traking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateTimeField()),
                ('reviewed_date', models.DateTimeField()),
                ('expected_resolve_date', models.DateTimeField()),
                ('work_start_date', models.DateTimeField()),
                ('work_end_date', models.DateTimeField()),
                ('complain_closed_date', models.DateTimeField()),
                ('complain_reopened_date', models.DateTimeField()),
                ('staff_complain_close_status', models.BooleanField(default=False)),
                ('user_complain_close_status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fk_complain_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complain_app.complain')),
            ],
        ),
        migrations.AddField(
            model_name='complain',
            name='fk_complain_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complain_app.complain_category'),
        ),
        migrations.AddField(
            model_name='complain',
            name='fk_department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complain_app.department'),
        ),
        migrations.AddField(
            model_name='complain',
            name='fk_organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complain_app.organization'),
        ),
    ]
