# Generated by Django 4.2.4 on 2023-11-03 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_alter_customuser_user_type'),
        ('complain_app', '0003_complain_fk_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='complain',
            name='complain_priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Low', max_length=100),
        ),
        migrations.AddField(
            model_name='complain',
            name='complain_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved'), ('Re opened', 'Re opened')], default='Pending', max_length=100),
        ),
        migrations.RemoveField(
            model_name='complain',
            name='after_complain_resolved_file',
        ),
        migrations.RemoveField(
            model_name='complain',
            name='before_complain_resolved_file',
        ),
        migrations.AlterField(
            model_name='complain',
            name='fk_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_app.staffuser'),
        ),
        migrations.AddField(
            model_name='complain',
            name='after_complain_resolved_file',
            field=models.ManyToManyField(blank=True, null=True, to='complain_app.after_complain_resolved_file'),
        ),
        migrations.AddField(
            model_name='complain',
            name='before_complain_resolved_file',
            field=models.ManyToManyField(blank=True, null=True, to='complain_app.before_complain_resolved_file'),
        ),
    ]
