# Generated by Django 4.2.4 on 2023-11-03 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_staffuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('user', 'user'), ('staff', 'staff'), ('admin', 'admin')], default='user', max_length=150),
        ),
    ]
